[package]
name = "livestream-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive"] }
futures = "0.3"
m3u8-rs = "4.0"
rand = "0.8"
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
reqwest-middleware = "0.1"
reqwest-retry = "0.1"
tokio = { version = "1.19", features = ["full"] }
